# Page settings

baseurl = "https://cameronbriar.com/resume/"
languageCode = "en-us"
title = "Cameron Briar | Resume"
theme = "hugo-orbit-theme"
#googleAnalytics = "UA-XXXXXXX-Y"

disableRSS = true
disableSitemap = true
disable404 = true

[params]

    description = "Resume for Cameron Briar, Site Reliability Engineer"
    author = "Cameron Briar"
    styles = "styles-7.css"

    [params.profile]
        name = "Cameron Briar"
        tagline = "Software Scientist"
        avatar = "profile.png"

    [params.contact]
        enable = true
        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: hi@cameronbriar.com"
        title = "hi@cameronbriar.com"
        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+5597971882"
        title = "+15597971882"
        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://cameronbriar.com"
        title = "cameronbriar.com"
        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/cameronbriar"
        title = "/cameronbriar"

    [params.education]
        enable = true
        title = "Education"
        [[params.education.list]]
        degree = "BS, Computer Science"
        college = "Fresno State, California"
        dates = "2012"

    [params.language]
        enable = true
        title = "Technologies"
        [[params.language.list]]
        language="Python"
        level="scikit-learn, scipy, numpy, pandas"
        [[params.language.list]]
        language="JavaScript"
        level="React-Native, Vue.js, Angular"
        [[params.language.list]]
        language="Linux"
        level="RHEL, Debian"
        [[params.language.list]]
        language="Data Science"
        level="Python, Spark, Octave, R, Jupyter, Visidata, GNU Radio"
        [[params.language.list]]
        language="Version Control"
        level="Git"
        [[params.language.list]]
        language="Databases"
        level="PostgreSQL, SQLite, MySQL, MongoDB, Redis"
        [[params.language.list]]
        language="Config. Management"
        level="Ansible, Chef, Salt, FSS"
        [[params.language.list]]
        language="Cloud Computing"
        level="Google, AWS, Rackspace, IBM SoftLayer"
        [[params.language.list]]
        language="Other Languages"
        level="Bash, Scala, C++, Obj-C, Swift, Java, PowerShell"

    [params.interests]
        enable = true
        title = "Pursuits"
        [[params.interests.list]]
        interest = "Statistical Learning"
        [[params.interests.list]]
        interest = "Data Science"
        [[params.interests.list]]
        interest = "Software-Defined Radio"
        [[params.interests.list]]
        interest = "Research & Development"
        [[params.interests.list]]
        interest = "Space"
        [[params.interests.list]]
        interest = "Libre Software"
        [[params.interests.list]]
        interest = "Problem Solving"

    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "A curious and diligent software engineer seeking to apply machine learning techniques to mobile applications and systems reliability. <div class='quote'>Cameron is professional, user-focused, and constantly learning and improving -- not just himself and our software, but also the tools other developers use. He has no problem thinking big picture while maintaining focus on the problem at hand. Despite having his responsibilities multiplied, he's still responsive to requests for recommendations or assistance. He's also saved my ass on at least a couple of occasions and has likely done the same for others around here. I think Cameron is a developer worthy of others emulating and should continue to be recognized for his outstanding work.</div><p><small>Chief Architect, FocusVision, 2016</small>"

    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"
        [[params.jobs.list]]
        position = "Bridgewater Associates"
        dates = "Jul 2017 - Present"
        company = "Site Reliability Engineer"
        details = "Maintain and improve service reliability through automation and effective systems support. I play a key role in reducing incident time-to-resolution, cognitive load, and human error by introducing more efficient operational procedures. I'm able to increase the accuracy and rate of service failure detection through the continuous reduction of signal:noise ratios in service monitoring systems."
        first = true
        subsection = false
        [[params.jobs.list]]
        position = "FocusVision"
        dates = "Nov 2015 - Dec 2016"
        company = "Site Reliability Engineer"
        details = "Introduced self-healing components that supported a positive increase in service uptime and reliability -- which significantly reduced the toil associated with being on-call. Focused on a breadth of areas related to systems infrastructure, deployment, security, and testing. Developed tools that enabled the business and its customers, increasing their ability to self-serve and remain productive while reducing the costs associated with knowledge sinks."
        first = true
        subsection = false
        [[params.jobs.list]]
        position = ""
        dates = "Jun 2014 - Nov 2015"
        company = "Software Engineer"
        details = "As a full-stack engineer, I used agile, test-driven approaches to develop stable APIs and feature-rich applications. I made large contributions to the design, implementation, security, automation, testing, and elimination of bugs in our system stack (from development to deployment)."
        first = false
        subsection = true
        [[params.jobs.list]]
        position = ""
        dates = "Nov 2013 - Jun 2014"
        company = "Technical Writer"
        details = "I combined accuracy, clarity, and brevity to curate technical documentation that was actionable, realistic, and organized. Having been in the trenches of survey programming, I authored and maintained an entire end-to-end guide on how to best work with the technology."
        first = false
        subsection = true
        [[params.jobs.list]]
        position = ""
        dates = "Aug 2012 - Nov 2013"
        company = "Survey Programmer"
        details = "Developed dynamic, interactive web applications to collect data across millions of respondents. Carefully implemented the logic and desired behavior that turned questionnaires into data collecting systems that were cross-browser, cross-device, ADA approved, and secure."
        first = false
        subsection = true
        [[params.jobs.list]]
        position = "Bitwise Industries"
        dates = "Feb 2016 - Apr 2016"
        company = "JavaScript Instructor"
        details = "While simultaneously working as an SRE @ FocusVision, I worked as a contractor to teach a six-week course on the fundamentals of JavaScript and programming. I gained a wholesome appreciation for those who are able to curate lesson plans that cater to the speeds, ability, and passion of the entire class."
        first = true
        subsection = false
        [[params.jobs.list]]
        position = "California State University, Fresno"
        dates = "Jan 2012 - Jul 2016"
        company = "Research & Development"
        details = "During my senior year in college and in partnership with the Nation Sciece Foundation, I developed FALT (Fresno Audiovisual Lexicon Tool) -- a system to perform lexical analysis on the similarities of phonemic and visemic communication."
        first = true
        subsection = false
        [[params.jobs.list]]
        position = ""
        dates = "Mar 2010 - Feb 2012"
        company = "IT Help Desk Technician"
        details = "Provided first class technical support to the entire campus."
        first = false
        subsection = true

    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "In Development"
        intro = ""
        [[params.projects.list]]
        title = "Radio Security"
        url = "#"
        tagline = "I'm eagerly working to understand how radio and digital signal processing works as it relates to secure and insecure communications."
        [[params.projects.list]]
        title = "Flynt"
        url = "#"
        tagline = "A mobile application designed to leverage accelerometer and gyroscope data to support the training of free motion gestures."
        [[params.projects.list]]
        title = "Booksee"
        url = "#"
        tagline = "Leveraging computer vision and OCR, use Booksee to catalog all books on a bookshelf simply by scanning across the shelf with the device's camera."

    [params.footer]
        copyright = ""
